### ISSUE TITLE
[Bug]: Statue in force loaded area causes a crash when attempting to spawn an entity

### ISSUE THREAD

**Issue by jasminexs** [svennieke/StatuesMod#82] opened 2023-03-14 20:02 UTC
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

43.2.4

### Minecraft version

1.19.2

### Mod version

0.3.2.1

### Java version

18.0.2.1

### Issue Description

Pretty much as the title says. I left a statue in the overworld in force-loaded chunks (FTB chunks) which had the mob spawner upgrade. When it tried to spawn an enderman, the game crashed.

### Additional Information

https://pastebin.com/swm3mZAd

**Comment by Mrbysco** [comment] 2023-03-14 20:05
Duplicate of #81 and fixed in https://github.com/ShyNieke/StatuesMod/commit/5a2321ca8e98301fb67612b81e5064ade45c9899

It's related to the mob killer upgrade hurting the mob and the mob trying to check if it can attack the attacker, which is trying to check the scoreboard but it can't due to how the fake player is setup. I've fixed this for future versions

**Closed as completed** 2023-04-07 17:48 UTC
Labels: bug
